# Generated by Django 4.0.1 on 2022-01-07 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_anime_slug'),
        ('store', '0002_delete_reviewrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='anime',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='anime.anime'),
        ),
    ]
