# Generated by Django 3.0.3 on 2022-01-06 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_auto_20220104_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_name', models.CharField(max_length=255)),
                ('anime_popularity', models.SmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='anime_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.AnimeName'),
        ),
    ]
