# Generated by Django 3.0.3 on 2022-01-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_auto_20220106_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animename',
            name='anime_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='animename',
            name='anime_popularity',
            field=models.SmallIntegerField(default=0),
        ),
    ]
