# Generated by Django 4.0.1 on 2022-01-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_coupon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnimeName',
            new_name='Anime',
        ),
    ]
