# Generated by Django 4.0.1 on 2022-01-07 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_rename_animename_anime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='anime_name',
            new_name='anime',
        ),
    ]
