# Generated by Django 4.0.1 on 2022-01-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_name', models.CharField(max_length=255, unique=True)),
                ('coupon_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
            ],
        ),
    ]
