# Generated by Django 4.0.1 on 2022-01-07 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_remove_reviewrating_review_image_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='ReviewImage',
        ),
    ]
