# Generated by Django 4.0.1 on 2022-01-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
