# Generated by Django 4.0.1 on 2022-01-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_anime_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='anime_description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
